### ISSUE TITLE
how to use gmx_mpi grompp command in gromacs VERSION 5.1.4 

### ISSUE THREAD

**Issue by vas2201** [GiovanniBussi/plumed2#3]
Hi Gromacs/Plumed users,
I am trying to Generate scaled topologies for Using Hamiltonian replica exchange with GROMACS. I am following online document. 
https://plumed.github.io/doc-v2.4/user-doc/html/hrex.html
so i have to use following command to genrate the .tpr file. 
grompp -p topol-scaled.top -o topol-scaled.tpr

I am getting following error, Looks like gmx_mpi grompp not implemented in gromacs-5.14 version.
[srp106@hpc1 bin]$ gmx grompp -p topol-scaled.top -o topol-scaled.tpr
                  :-) GROMACS - gmx grompp, VERSION 5.1.4 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov  Herman J.C. Berendsen    Par Bjelkmar   
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra   Sebastian Fritsch 
  Gerrit Groenhof   Christoph Junghans   Anca Hamuraru    Vincent Hindriksen
 Dimitrios Karkoulis    Peter Kasson        Jiri Kraus      Carsten Kutzner  
    Per Larsson      Justin A. Lemkul   Magnus Lundborg   Pieter Meulenhoff 
   Erik Marklund      Teemu Murtola       Szilard Pall       Sander Pronk   
   Roland Schulz     Alexey Shvetsov     Michael Shirts     Alfons Sijbers  
   Peter Tieleman    Teemu Virolainen  Christian Wennberg    Maarten Wolf   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2015, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, VERSION 5.1.4
Executable:   /home/srp106/software/gromacs-5.1.4/gmxbuild/bin/gmx
Data prefix:  /home/srp106/software/gromacs-5.1.4/gmxbuild
Command line:
  gmx grompp -p topol-scaled.top -o topol-scaled.tpr

-------------------------------------------------------
Program:     gmx grompp, VERSION 5.1.4
Source file: src/gromacs/commandline/cmdlineparser.cpp (line 234)
Function:    void gmx::CommandLineParser::parse(int*, char**)

Error in user input:
Invalid command-line options
  In command-line option -p
    File 'topol-scaled.top' does not exist or is not accessible.

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------

 so could please suggest me needful to convert the file from processed.top file to topol-scaled.tpr  using gmx_mpi command?

**Comment by GiovanniBussi** [comment]
Hi I think the option is `gmx_mpi grompp -pp` (with two `p`'s)
